# Generated by Django 5.2.5 on 2025-09-04 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuthorModel',
            new_name='Author',
        ),
        migrations.RenameModel(
            old_name='BookModel',
            new_name='Book',
        ),
        migrations.RenameModel(
            old_name='LibrarianModel',
            new_name='Librarian',
        ),
        migrations.RenameModel(
            old_name='LibraryModel',
            new_name='Library',
        ),
    ]
