# Generated by Django 5.2.5 on 2025-08-31 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_alter_book_author_alter_book_pulication_year_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='pulication_year',
            new_name='publication_year',
        ),
    ]
